CREATE TABLE IF NOT EXISTS models (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(100) UNIQUE NOT NULL,
  display_name VARCHAR(100),
  enabled TINYINT(1) DEFAULT 1
);

CREATE TABLE IF NOT EXISTS classification_requests (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  req_id VARCHAR(64) UNIQUE NOT NULL,
  text MEDIUMTEXT NOT NULL,
  model_version VARCHAR(100) NOT NULL,
  label ENUM('DEFAMATION','NON_DEFAMATION') NOT NULL,
  confidence DECIMAL(5,4) DEFAULT 0.0000,
  rationale TEXT,
  latency_ms INT DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS cases (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  situation TEXT NOT NULL,
  verdict ENUM('유죄','무죄') NOT NULL,
  sentence VARCHAR(120),
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
